return {
	{
		"nvim-telescope/telescope.nvim",
		cmd = "Telescope",
		version = false,
		dependencies = {
			"nvim-lua/plenary.nvim",
			"lpoto/telescope-tasks.nvim",
		},
		keys = {
			{
				"<leader>ff",
				function()
					require("telescope.builtin").find_files()
				end,
			},
			{
				"<leader>fs",
				function()
					require("telescope.builtin").grep_string()
				end,
			},
			{
				"<leader>fg",
				function()
					require("telescope.builtin").live_grep()
				end,
			},
			{
				"<leader>fb",
				function()
					require("telescope.builtin").buffers()
				end,
			},
			{
				"<leader>fh",
				function()
					require("telescope.builtin").help_tags()
				end,
			},
			{
				"<leader>fr",
				function()
					require("telescope.builtin").lsp_references()
				end,
			},
			{
				"<leader>fc",
				function()
					require("telescope.builtin").git_commits()
				end,
			},
			{
				"<leader>ft",
				function()
					require("telescope.builtin").git_status()
				end,
			},
			{
				"<leader>fm",
				function()
					require("telescope").load_extension("harpoon")
					require("telescope").extensions.harpoon.marks()
				end,
			},
			{
				"<leader>fo",
				function()
					require("telescope").extensions.tasks.tasks()
				end,
			},
		},
		config = function()
			require("telescope").load_extension("tasks")
			local default = require("telescope").extensions.tasks.generators.default
			default.all()
		end,
	},
}
