#!/usr/bin/env bash

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ASSET_DIR="$HOME/.config/sketchybar/assets"

FONT="Inconsolata"
ICON_FONT="Inconsolata Nerd Font"

BAR=(
  height=34
  color=0x44000000
  blur_radius=16
  position=top
  shadow=off
  padding_left=0
  padding_right=0
)

DEFAULTS=(
  updates=when_shown
  icon.font="$ICON_FONT:Bold:14.0"
  icon.color=0xff24273a
  icon.padding_left=16
  icon.padding_right=5
  label.font="$FONT:Bold:14.0"
  label.color=0xff24273a
  label.padding_left=5
  label.padding_right=16
  background.height=34
  background.padding_left=2
  background.padding_right=2
)

sketchybar --bar "${BAR[@]}"
sketchybar --default "${DEFAULTS[@]}"

source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"

sketchybar --update
