#!/usr/bin/env bash

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

BAR_HEIGHT=$(sketchybar -m --query bar | jq -r '.height')

GENERAL=(
  external_bar all:"${BAR_HEIGHT}":0
  split_type auto
  split_ratio 0.5
  auto_balance off
  insert_feedback_color 0xffee99a0
)

WINDOWS=(
  window_placement second_child
  window_topmost off
  window_shadow off
  window_opacity off
  window_animation_duration 0.0
  window_origin_display focused
)

BORDERS=(
  window_border on
  window_border_blur off
  window_border_hidpi on
  window_border_width 4
  window_border_radius 12
  active_window_border_color 0xff8bd5ca
  normal_window_border_color 0xffc6a0f6
)

LAYOUT=(
  layout bsp
  top_padding 8 
  bottom_padding 8
  left_padding 8
  right_padding 8
  window_gap 8
)

MOUSE=(
  mouse_modifier alt
  mouse_action1 move
  mouse_action2 resize
  mouse_drop_action swap
)

yabai -m config "${GENERAL[@]}"
yabai -m config "${WINDOWS[@]}"
yabai -m config "${BORDERS[@]}"
yabai -m config "${LAYOUT[@]}"
yabai -m config "${MOUSE[@]}"

yabai -m rule --add app!="^(Google Chrome|Discord|Obsidian|Spotify|WezTerm|wezterm-gui|VSCodium)$" manage=off
